# déploie la configuration RCLONE et BORGMATIC
---
- name: déploie la configuration RCLONE et BORGMATIC
  hosts: all

  vars:
    racine: /home/debian/backup # je décale dans un sous repertoire, car le risque de casser les droits de ~debian empeche toute cnx SSL ensuite
    borgRepository: "{{ racine }}/borg-repository"
    config: "{{ racine }}/borg-rclone"
    mountPoint: "{{ racine }}/mnt"
    OneDrive: "{{ mountPoint }}/OneDrive"
    OneDriveB: "{{ mountPoint }}/OneDriveB"
  
  become: true

  tasks:
    - name: vérifie que le répertoire de destination existe
      file:
        path: "{{ racine }}"
        state: directory
        owner: debian 
        group: debian
        mode: 0755

    - name: effectue la synchronisation
      ansible.posix.synchronize:
        src: ./arbo/
        dest: "{{ racine }}"
        recursive: yes
        delete: no # avec yes, j’ai tout effacé dans mon home directory… :(
        rsync_path: rsync # si on ne met pas ça, par défaut il tente un "sudo rsync etc." qui foire

    - name: remet les droits correctement pour "{{ racine }}"
      file:
        path: "{{ racine }}"
        state: directory
        owner: debian 
        group: debian
        mode: 0755

# curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
# echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
# sudo apt-get update
# sudo apt-get install docker-ce docker-ce-cli containerd.io    - name: Install packages nécessaires à DOCKER
    - name: vérifie que la source de paquet pour docker est dans /etc/apt/sources.list.d/docker.list
      shell: curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      args:
        creates: /usr/share/keyrings/docker-archive-keyring.gpg
    - name: installe docker au besoin
      apt:
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg', 'lsb-release', 'docker-ce', 'docker-ce-cli', 'containerd.io']
        state: present
        update_cache: yes
        cache_valid_time: 0

#   docker stop borgmatic && docker rm borgmatic
# docker run \
#   --detach --name borgmatic \
#   -v "/mnt/OneDrive/Personnel/partition et musique/music sandbox:/mnt/source:ro" \
#   -v /home/christophe/etc/data/repository:/mnt/borg-repository \
#   -v /home/christophe/etc/data/borgmatic.d:/etc/borgmatic.d/ \
#   -v /home/christophe/etc/data/.config/borg:/root/.config/borg \
#   -v /home/christophe/etc/data/.ssh:/root/.ssh \
#   -v /home/christophe/etc/data/.cache/borg:/root/.cache/borg \
#   -e TZ=Europe/Paris \
#   ghcr.io/borgmatic-collective/borgmatic
    - name: lance un container borgmatic
      docker_container:
        name: borgmatic
        image: ghcr.io/borgmatic-collective/borgmatic:latest
        state: started
        restart_policy: no
        detach: true
        env:
          TZ: Europe/Paris
        volumes:
          - "{{ mountPoint }}:/mnt/source:ro"
          - "{{ borgRepository }}:/mnt/borg-repository"
          - "{{ config }}:/etc/borgmatic.d"
          - "{{ config }}:/root/.config/borg"
          - "{{ config }}:/root/.ssh"
          - "{{ config }}:/root/.cache/borg"
        #command: borgmatic init --encryption none -v 2


# docker stop rclone && docker rm rclone
# docker run -d \
#     --name=rclone \
#     --cap-add SYS_ADMIN \
#     --device /dev/fuse \
#     --security-opt apparmor=unconfined \
#     -v ${DOCKER_ROOT}/home/christophe/.config/rclone:/config \
#     -v ${DOCKER_ROOT}/home/christophe/etc/data.rclone/log:/log \
#     -v ${DOCKER_ROOT}/home/christophe/etc/data.rclone/cache:/cache \
#     -v /mnt/OneDrive:/data:shared \
#     -e TZ=Europe/Paris \
#     -e RCLONE_REMOTE_PATH=OneDrive:/\
#     -e RCLONE_MOUNT_USER_OPTS="--read-only --vfs-cache-mode=full --no-checksum --no-modtime --allow-non-empty" \
#     wiserain/rclone

    - name: lance un container rclone
      docker_container:
        name: rclone
        image: wiserain/rclone
        state: started
        detach: true
        restart_policy: no
        env:
          TZ: Europe/Paris
          RCLONE_MOUNT_USER_OPTS: --read-only --vfs-cache-mode full --no-modtime --no-checksum --allow-non-empty
          RCLONE_REMOTE_PATH: OneDrive:/
        capabilities:
          - SYS_ADMIN
        devices:
          - "/dev/fuse"
        security_opts:
          - apparmor:unconfined
        volumes:
          - "{{ OneDrive }}:/data:shared"
          - "{{ OneDriveB }}:/data2:shared"
          - "{{ config }}:/config"
          - "{{ config }}:/log"
          - "{{ config }}:/cache"
# # Ensuite il faudrait monter OneDriveB par dessus:
# docker exec -t rclone bash -c "rclone mount OneDriveB: /data2 \
#  --uid=${PUID:-911} --gid=${PGID:-911} --cache-dir=/cache --use-mmap --allow-other --umask=002 \
#   --rc  --rc-no-auth  --rc-addr=:5576 --daemon  ${RCLONE_MOUNT_USER_OPTS} "    
    
    - name: monter OneDriveB en plus de OneDrive
      community.docker.docker_container_exec:
        container: rclone
        command: "sh -c 'rclone mount OneDriveB: /data2 --uid=911 --gid=911 --cache-dir=/cache --use-mmap --allow-other --umask=002 --rc --rc-no-auth --rc-addr=:5576 --read-only --vfs-cache-mode=full --no-checksum --no-modtime --allow-non-empty > /log/mount-OneDriveB.log 2>&1 &'"
