# List of source directories and files to back up. Globs and tildes
# are expanded. Do not backslash spaces in path names.
source_directories:
    # tout le drive de Beatrice
    - /mnt/source/OneDriveB
    # uniquement la partie "Personnel" du drive de Christophe - le reste est supposé recopié une bonne fois
    - /mnt/source/OneDrive/Personnel

# A required list of local or remote repositories with paths and
# optional labels (which can be used with the --repository flag to
# select a repository). Tildes are expanded. Multiple repositories are
# backed up to in sequence. Borg placeholders can be used. See the
# output of "borg help placeholders" for details. See ssh_command for
# SSH options like identity file or port. If systemd service is used,
# then add local repository paths in the systemd service file to the
# ReadWritePaths list. Prior to borgmatic 1.7.10, repositories was a
# list of plain path strings.
repositories:
    - path: /mnt/borg-repository

exclude_patterns:
    - '*.pyc'
    - '*/site-packages/*'
    - '*/venv/*'
    - '*/.venv/*'
    - '*.tmp'
    - '*/Free Opensource Softwares/*'
    # - '*/.vim*.tmp'
    # - /etc/ssl
    # - /home/user/path with spaces

# Keep all archives within this time interval. See "skip_actions" for
# disabling pruning altogether.
# Number of daily archives to keep.
# keep_daily: 7

# Number of weekly archives to keep.
keep_weekly: 5

# Number of monthly archives to keep.
keep_monthly: 12

# Number of yearly archives to keep.
keep_yearly: 2
