# List of source directories and files to back up. Globs and tildes
# are expanded. Do not backslash spaces in path names.
source_directories:
    # tout le drive de Beatrice
    - /mnt/source/OneDriveB
    # uniquement la partie "Personnel" du drive de Christophe - le reste est supposé recopié une bonne fois
    - /mnt/source/OneDrive/Personnel

# A required list of local or remote repositories with paths and
# optional labels (which can be used with the --repository flag to
# select a repository). Tildes are expanded. Multiple repositories are
# backed up to in sequence. Borg placeholders can be used. See the
# output of "borg help placeholders" for details. See ssh_command for
# SSH options like identity file or port. If systemd service is used,
# then add local repository paths in the systemd service file to the
# ReadWritePaths list. Prior to borgmatic 1.7.10, repositories was a
# list of plain path strings.
repositories:
    - path: /mnt/borg-repository

exclude_patterns:
    - '*.pyc'
    - '*/site-packages/*'
    - '*/venv/*'
    - '*/.venv/*'
    - '*.tmp'
    - '*/Free Opensource Softwares/*'
    # - '*/.vim*.tmp'
    # - /etc/ssl
    # - /home/user/path with spaces

# Keep all archives within this time interval. See "skip_actions" for
# disabling pruning altogether.
# Number of daily archives to keep.
# keep_daily: 7

# Number of weekly archives to keep.
keep_weekly: 5

# Number of monthly archives to keep.
keep_monthly: 12

# Number of yearly archives to keep.
keep_yearly: 2

ntfy:
    # The topic to publish to. See https://ntfy.sh/docs/publish/
    # for details.
    topic: ui6now

    # The address of your self-hosted ntfy.sh instance.
    server: https://ntfy.sh

    # The username used for authentication.
    # username: testuser

    # The password used for authentication.
    # password: fakepassword

    # An ntfy access token to authenticate with instead of
    # username/password.
    # access_token: tk_AgQdq7mVBoFD37zQVN29RhuMzNIz2

    start:
        # The title of the message.
        title: Borg...

        # The message body to publish.
        message: Your backups have started.

        # The priority to set.
        # priority: urgent

        # Tags to attach to the message.
        tags: borgmatic

    finish:
        # The title of the message.
        title: Borg!

        # The message body to publish.
        message: Your backups were completed successfully.

        # The priority to set.
        # priority: urgent

        # Tags to attach to the message.
        tags: borgmatic,+1

    fail:
        # The title of the message.
        title: Borg :/

        # The message body to publish.
        message: Your backups have failed.

        # The priority to set.
        priority: urgent

        # Tags to attach to the message.
        tags: borgmatic,-1,skull

    # List of one or more monitoring states to ping for: "start",
    # "finish", and/or "fail". Defaults to pinging for failure
    # only.
    states:
        - start
        - finish
        - fail